version: "3"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    env_file:
      - .env
    command: >
      sh -c "alembic upgrade head && python main.py"
    restart: on-failure